services:
  db:
    image: mysql
    container_name: companydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: companydb
      MYSQL_USER: fazt
      MYSQL_PASSWORD: faztpassword
    ports:
      - 3307:3306
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    